<a href="https://colab.research.google.com/github/Safkat16/data-science-toolkit/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("pardeep19singh/icc-mens-world-cup-2023")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/pardeep19singh/icc-mens-world-cup-2023/11.archive...

100%|██████████| 152k/152k [00:00<00:00, 402kB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/pardeep19singh/icc-mens-world-cup-2023/versions/11

In [2]:
#1.Find some real dataset. Load it on Colab, Kaggle etc. Try to visualize some of it
import os
import pandas as pd

print(os.listdir(path))

['deliveries.csv', 'matches.csv', 'points_table.csv']

In [3]:

import os
os.chdir(path)
import pandas as pd
df=pd.read_csv("matches.csv")
print(df.head())

    season         team1        team2        date  match_number  \
0  2023/24       England  New Zealand  2023/10/05             1
1  2023/24      Pakistan  Netherlands  2023/10/06             2
2  2023/24   Afghanistan   Bangladesh  2023/10/07             3
3  2023/24  South Africa    Sri Lanka  2023/10/07             4
4  2023/24     Australia        India  2023/10/08             5

                                          venue        city  toss_winner  \
0                         Narendra Modi Stadium   Ahmedabad  New Zealand
1            Rajiv Gandhi International Stadium   Hyderabad  Netherlands
2  Himachal Pradesh Cricket Association Stadium  Dharamsala   Bangladesh
3                          Arun Jaitley Stadium       Delhi    Sri Lanka
4                        MA Chidambaram Stadium     Chennai    Australia

  toss_decision     player_of_match          umpire1           umpire2  \
0         field          R Ravindra  HDPK Dharmasena       Nitin Menon
1         field        Saud Shakeel     AT Holdstock          CM Brown
2         field  Mehedi Hasan Miraz        JS Wilson   HDPK Dharmasena
3         field          AK Markram   RK Illingworth      Sharfuddoula
4           bat            KL Rahul      CB Gaffaney  RA Kettleborough

  reserve_umpire  match_referee        winner  winner_runs  winner_wickets  \
0   Sharfuddoula      J Srinath   New Zealand          NaN             9.0
1     PR Reiffel       JJ Crowe      Pakistan         81.0             NaN
2      M Erasmus     AJ Pycroft    Bangladesh          NaN             6.0
3       AG Wharf      J Srinath  South Africa        102.0             NaN
4   AT Holdstock  RB Richardson         India          NaN             6.0

  match_type
0      Group
1      Group
2      Group
3      Group
4      Group

In [4]:
#2.Evaluate if the data is good or not. Does it have enough samples?
print("Number of samples:", len(df))
print("Missing Values:")
print(df.isnull().sum())

total samples: 48
Missing Values:
season              0
team1               0
team2               0
date                0
match_number        0
venue               0
city                0
toss_winner         0
toss_decision       0
player_of_match     0
umpire1             0
umpire2             0
reserve_umpire      1
match_referee       0
winner              0
winner_runs        24
winner_wickets     24
match_type          0
dtype: int64

The dataset is from Kaggle.It has 48 samples and 3 of them have missing values.However,they have no impact on overall conclusion.So,the dataset is pretty good and it has enough samples.

In [20]:
#3.How many features does it have? Is it enough?
print("Total columns:", df.shape[0])
print(df.columns.tolist())

Total columns: 48
['season', 'team1', 'team2', 'date', 'match_number', 'venue', 'city', 'toss_winner', 'toss_decision', 'player_of_match', 'umpire1', 'umpire2', 'reserve_umpire', 'match_referee', 'winner', 'winner_runs', 'winner_wickets', 'match_type']

The Dataset contains 48 features.It Is good enough for any decision

In [24]:
 #4.How many samples/observation does it have? Is it enough?
print("Number of samples (rows):",df.shape[1])

Number of samples (rows): 18

The Dataset has 48 rows.Since It contains all relevant data regarding the tournament,it is enough to draw any conclusion.

In [7]:
#5.What are the datatypes does the dataset consist of?

import os
os.chdir(path)
import pandas as pd
df=pd.read_csv("matches.csv")
print(df.dtypes)
print(df.dtypes.value_counts())

season              object
team1               object
team2               object
date                object
match_number         int64
venue               object
city                object
toss_winner         object
toss_decision       object
player_of_match     object
umpire1             object
umpire2             object
reserve_umpire      object
match_referee       object
winner              object
winner_runs        float64
winner_wickets     float64
match_type          object
dtype: object
object     15
float64     2
int64       1
Name: count, dtype: int64

In [8]:
 #6.How many columns have null values? If yes, which column, which rows

df.isnull().sum()

season              0
team1               0
team2               0
date                0
match_number        0
venue               0
city                0
toss_winner         0
toss_decision       0
player_of_match     0
umpire1             0
umpire2             0
reserve_umpire      1
match_referee       0
winner              0
winner_runs        24
winner_wickets     24
match_type          0
dtype: int64

In [9]:
null_cols = df.columns[df.isnull().any()]

print("Number of columns with nulls:", len(null_cols))
print("Columns:", null_cols.tolist())

Number of columns with nulls: 3
Columns: ['reserve_umpire', 'winner_runs', 'winner_wickets']

In [10]:
rows_with_nulls = df[df.isnull().any(axis=1)]
print("Number of rows with nulls:", len(rows_with_nulls))
rows_with_nulls

Number of rows with nulls: 48

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
0,2023/24,England,New Zealand,2023/10/05,1,Narendra Modi Stadium,Ahmedabad,New Zealand,field,R Ravindra,HDPK Dharmasena,Nitin Menon,Sharfuddoula,J Srinath,New Zealand,NaN,9.0,Group
1,2023/24,Pakistan,Netherlands,2023/10/06,2,Rajiv Gandhi International Stadium,Hyderabad,Netherlands,field,Saud Shakeel,AT Holdstock,CM Brown,PR Reiffel,JJ Crowe,Pakistan,81.0,NaN,Group
2,2023/24,Afghanistan,Bangladesh,2023/10/07,3,Himachal Pradesh Cricket Association Stadium,Dharamsala,Bangladesh,field,Mehedi Hasan Miraz,JS Wilson,HDPK Dharmasena,M Erasmus,AJ Pycroft,Bangladesh,NaN,6.0,Group
3,2023/24,South Africa,Sri Lanka,2023/10/07,4,Arun Jaitley Stadium,Delhi,Sri Lanka,field,AK Markram,RK Illingworth,Sharfuddoula,AG Wharf,J Srinath,South Africa,102.0,NaN,Group
4,2023/24,Australia,India,2023/10/08,5,MA Chidambaram Stadium,Chennai,Australia,bat,KL Rahul,CB Gaffaney,RA Kettleborough,AT Holdstock,RB Richardson,India,NaN,6.0,Group
5,2023/24,New Zealand,Netherlands,2023/10/09,6,Rajiv Gandhi International Stadium,Hyderabad,Netherlands,field,MJ Santner,PR Reiffel,RJ Tucker,Nitin Menon,AJ Pycroft,New Zealand,99.0,NaN,Group
6,2023/24,England,Bangladesh,2023/10/10,7,Himachal Pradesh Cricket Association Stadium,Dharamsala,Bangladesh,field,DJ Malan,Ahsan Raza,P Wilson,HDPK Dharmasena,J Srinath,England,137.0,NaN,Group
7,2023/24,Sri Lanka,Pakistan,2023/10/10,8,Rajiv Gandhi International Stadium,Hyderabad,Sri Lanka,bat,Mohammad Rizwan,AG Wharf,CB Gaffaney,RJ Tucker,AJ Pycroft,Pakistan,NaN,6.0,Group
8,2023/24,Afghanistan,India,2023/10/11,9,Arun Jaitley Stadium,Delhi,Afghanistan,bat,RG Sharma,MA Gough,PR Reiffel,Sharfuddoula,JJ Crowe,India,NaN,8.0,Group
9,2023/24,South Africa,Australia,2023/10/12,10,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Australia,field,Q de Kock,JS Wilson,RK Illingworth,CM Brown,J Srinath,South Africa,134.0,NaN,Group
10,2023/24,Bangladesh,New Zealand,2023/10/13,11,MA Chidambaram Stadium,Chennai,New Zealand,field,LH Ferguson,HDPK Dharmasena,Nitin Menon,AG Wharf,RB Richardson,New Zealand,NaN,8.0,Group
11,2023/24,Pakistan,India,2023/10/14,12,Narendra Modi Stadium,Ahmedabad,India,field,JJ Bumrah,M Erasmus,RK Illingworth,CB Gaffaney,AJ Pycroft,India,NaN,7.0,Group
12,2023/24,Afghanistan,England,2023/10/15,13,Arun Jaitley Stadium,Delhi,England,field,Mujeeb Ur Rahman,RJ Tucker,Sharfuddoula,P Wilson,JJ Crowe,Afghanistan,69.0,NaN,Group
13,2023/24,Sri Lanka,Australia,2023/10/16,14,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sri Lanka,bat,A Zampa,CB Gaffaney,JS Wilson,NaN,RB Richardson,Australia,NaN,5.0,Group
14,2023/24,Netherlands,South Africa,2023/10/17,15,Himachal Pradesh Cricket Association Stadium,Dharamsala,South Africa,field,SA Edwards,MA Gough,RA Kettleborough,Ahsan Raza,JJ Crowe,Netherlands,38.0,NaN,Group
15,2023/24,New Zealand,Afghanistan,2023/10/18,16,MA Chidambaram Stadium,Chennai,Afghanistan,field,GD Phillips,JS Wilson,P Wilson,J Madanagopal,J Srinath,New Zealand,149.0,NaN,Group
16,2023/24,Bangladesh,India,2023/10/19,17,Maharashtra Cricket Association Stadium,Pune,Bangladesh,bat,V Kohli,AT Holdstock,RA Kettleborough,M Erasmus,AJ Pycroft,India,NaN,7.0,Group
17,2023/24,Australia,Pakistan,2023/10/20,18,M Chinnaswamy Stadium,Bengaluru,Pakistan,field,DA Warner,CM Brown,RK Illingworth,J Madanagopal,RB Richardson,Australia,62.0,NaN,Group
18,2023/24,Netherlands,Sri Lanka,2023/10/21,19,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Netherlands,bat,S Samarawickrama,Ahsan Raza,M Erasmus,CB Gaffaney,JJ Crowe,Sri Lanka,NaN,5.0,Group
19,2023/24,South Africa,England,2023/10/21,20,Wankhede Stadium,Mumbai,England,field,H Klaasen,HDPK Dharmasena,Nitin Menon,JS Wilson,J Srinath,South Africa,229.0,NaN,Group
20,2023/24,New Zealand,India,2023/10/22,21,Himachal Pradesh Cricket Association Stadium,Dharamsala,India,field,Mohammed Shami,AT Holdstock,MA Gough,Praveen Sen,AJ Pycroft,India,NaN,4.0,Group
21,2023/24,Pakistan,Afghanistan,2023/10/23,22,MA Chidambaram Stadium,Chennai,Pakistan,bat,Ibrahim Zadran,PR Reiffel,RJ Tucker,HDPK Dharmasena,RB Richardson,Afghanistan,NaN,8.0,Group
22,2023/24,South Africa,Bangladesh,2023/10/24,23,Wankhede Stadium,Mumbai,South Africa,bat,Q de Kock,Ahsan Raza,JS Wilson,KN Ananthapadmanabhan,JJ Crowe,South Africa,149.0,NaN,Group
23,2023/24,Australia,Netherlands,2023/10/25,24,Arun Jaitley Stadium,Delhi,Australia,bat,GJ Maxwell,MA Gough,Sharfuddoula,Nitin Menon,AJ Pycroft,Australia,309.0,NaN,Group
24,2023/24,England,Sri Lanka,2023/10/26,25,M Chinnaswamy Stadium,Bengaluru,England,bat,CBRLS Kumara,AT Holdstock,CM Brown,RJ Tucker,J Srinath,Sri Lanka,NaN,8.0,Group
25,2023/24,Pakistan,South Africa,2023/10/27,26,MA Chidambaram Stadium,Chennai,Pakistan,bat,T Shamsi,AG Wharf,PR Reiffel,RA Kettleborough,RB Richardson,South Africa,NaN,1.0,Group
26,2023/24,Australia,New Zealand,2023/10/28,27,Himachal Pradesh Cricket Association Stadium,Dharamsala,New Zealand,field,TM Head,M Erasmus,Sharfuddoula,MA Gough,AJ Pycroft,Australia,5.0,NaN,Group
27,2023/24,Netherlands,Bangladesh,2023/10/28,28,Eden Gardens,Kolkata,Netherlands,bat,PA van Meekeren,JS Wilson,P Wilson,CB Gaffaney,JJ Crowe,Netherlands,87.0,NaN,Group
28,2023/24,India,England,2023/10/29,29,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,England,field,RG Sharma,AT Holdstock,RJ Tucker,CM Brown,RB Richardson,India,100.0,NaN,Group
29,2023/24,Sri Lanka,Afghanistan,2023/10/30,30,Maharashtra Cricket Association Stadium,Pune,Afghanistan,field,Fazalhaq Farooqi,CB Gaffaney,RK Illingworth,M Erasmus,J Srinath,Afghanistan,NaN,7.0,Group
30,2023/24,Bangladesh,Pakistan,2023/10/31,31,Eden Gardens,Kolkata,Bangladesh,bat,Fakhar Zaman,Nitin Menon,RA Kettleborough,PR Reiffel,AJ Pycroft,Pakistan,NaN,7.0,Group
31,2023/24,South Africa,New Zealand,2023/11/01,32,Maharashtra Cricket Association Stadium,Pune,New Zealand,field,HE van der Dussen,Ahsan Raza,HDPK Dharmasena,P Wilson,RB Richardson,South Africa,190.0,NaN,Group
32,2023/24,India,Sri Lanka,2023/11/02,33,Wankhede Stadium,Mumbai,Sri Lanka,field,Mohammed Shami,CM Brown,PR Reiffel,RK Illingworth,JJ Crowe,India,302.0,NaN,Group
33,2023/24,Netherlands,Afghanistan,2023/11/03,34,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Netherlands,bat,Mohammad Nabi,Nitin Menon,Sharfuddoula,HDPK Dharmasena,J Srinath,Afghanistan,NaN,7.0,Group
34,2023/24,New Zealand,Pakistan,2023/11/04,35,M Chinnaswamy Stadium,Bengaluru,Pakistan,field,Fakhar Zaman,P Wilson,RA Kettleborough,JS Wilson,RB Richardson,Pakistan,21.0,NaN,Group
35,2023/24,Australia,England,2023/11/04,36,Narendra Modi Stadium,Ahmedabad,England,field,A Zampa,CB Gaffaney,M Erasmus,Ahsan Raza,JJ Crowe,Australia,33.0,NaN,Group
36,2023/24,India,South Africa,2023/11/05,37,Eden Gardens,Kolkata,India,bat,V Kohli,HDPK Dharmasena,PR Reiffel,AG Wharf,AJ Pycroft,India,243.0,NaN,Group
37,2023/24,Sri Lanka,Bangladesh,2023/11/06,38,Arun Jaitley Stadium,Delhi,Bangladesh,field,Shakib Al Hasan,M Erasmus,RK Illingworth,AT Holdstock,RB Richardson,Bangladesh,NaN,3.0,Group
38,2023/24,Afghanistan,Australia,2023/11/07,39,Wankhede Stadium,Mumbai,Afghanistan,bat,GJ Maxwell,AG Wharf,MA Gough,Sharfuddoula,JJ Crowe,Australia,NaN,3.0,Group
39,2023/24,England,Netherlands,2023/11/08,40,Maharashtra Cricket Association Stadium,Pune,England,bat,BA Stokes,Ahsan Raza,RJ Tucker,P Wilson,AJ Pycroft,England,160.0,NaN,Group
40,2023/24,Sri Lanka,New Zealand,2023/11/09,41,M Chinnaswamy Stadium,Bengaluru,New Zealand,field,TA Boult,AT Holdstock,JS Wilson,PR Reiffel,J Srinath,New Zealand,NaN,5.0,Group
41,2023/24,Afghanistan,South Africa,2023/11/10,42,Narendra Modi Stadium,Ahmedabad,Afghanistan,bat,HE van der Dussen,CM Brown,Nitin Menon,CB Gaffaney,JJ Crowe,South Africa,NaN,5.0,Group
42,2023/24,Bangladesh,Australia,2023/11/11,43,Maharashtra Cricket Association Stadium,Pune,Australia,field,MR Marsh,Ahsan Raza,M Erasmus,RA Kettleborough,AJ Pycroft,Australia,NaN,8.0,Group
43,2023/24,England,Pakistan,2023/11/11,44,Eden Gardens,Kolkata,England,bat,DJ Willey,P Wilson,RJ Tucker,PR Reiffel,J Srinath,England,93.0,NaN,Group
44,2023/24,India,Netherlands,2023/11/12,45,M Chinnaswamy Stadium,Bengaluru,India,bat,SS Iyer,CB Gaffaney,MA Gough,CM Brown,RB Richardson,India,160.0,NaN,Group
45,2023/24,India,New Zealand,2023/11/15,46,Wankhede Stadium,Mumbai,India,bat,Mohammed Shami,RK Illingworth,RJ Tucker,AT Holdstock,AJ Pycroft,India,70.0,NaN,Semi Final
46,2023/24,South Africa,Australia,2023/11/16,47,Eden Gardens,Kolkata,South Africa,bat,TM Head,Nitin Menon,RA Kettleborough,MA Gough,J Srinath,Australia,NaN,3.0,Semi Final
47,2023/24,India,Australia,2023/11/19,48,Narendra Modi Stadium,Ahmedabad,Australia,field,TM Head,RK Illingworth,RA Kettleborough,CB Gaffaney,AJ Pycroft,Australia,NaN,6.0,Final

In [16]:
#7.Which column is the feature, which is the target output?
target = "winner"
features = ["team1", "team2", "venue", "toss_winner", "toss_decision", "match_type"]

X = df[features]
y = df[target]

print("Target:", target)
print("Number of features:", len(features))
print("Features:", features)

Target: winner
Number of features: 6
Features: ['team1', 'team2', 'venue', 'toss_winner', 'toss_decision', 'match_type']

In [17]:
#8.Does it have missing values? If yes, which column, which row.
print("Missing Values:")
print(df.isnull().sum())
print("Rows with Missing Values:")
print(df[df.isnull().any(axis=1)])

Missing Values:
season              0
team1               0
team2               0
date                0
match_number        0
venue               0
city                0
toss_winner         0
toss_decision       0
player_of_match     0
umpire1             0
umpire2             0
reserve_umpire      1
match_referee       0
winner              0
winner_runs        24
winner_wickets     24
match_type          0
dtype: int64
Rows with Missing Values:
     season         team1         team2        date  match_number  \
0   2023/24       England   New Zealand  2023/10/05             1
1   2023/24      Pakistan   Netherlands  2023/10/06             2
2   2023/24   Afghanistan    Bangladesh  2023/10/07             3
3   2023/24  South Africa     Sri Lanka  2023/10/07             4
4   2023/24     Australia         India  2023/10/08             5
5   2023/24   New Zealand   Netherlands  2023/10/09             6
6   2023/24       England    Bangladesh  2023/10/10             7
7   2023/24     Sri Lanka      Pakistan  2023/10/10             8
8   2023/24   Afghanistan         India  2023/10/11             9
9   2023/24  South Africa     Australia  2023/10/12            10
10  2023/24    Bangladesh   New Zealand  2023/10/13            11
11  2023/24      Pakistan         India  2023/10/14            12
12  2023/24   Afghanistan       England  2023/10/15            13
13  2023/24     Sri Lanka     Australia  2023/10/16            14
14  2023/24   Netherlands  South Africa  2023/10/17            15
15  2023/24   New Zealand   Afghanistan  2023/10/18            16
16  2023/24    Bangladesh         India  2023/10/19            17
17  2023/24     Australia      Pakistan  2023/10/20            18
18  2023/24   Netherlands     Sri Lanka  2023/10/21            19
19  2023/24  South Africa       England  2023/10/21            20
20  2023/24   New Zealand         India  2023/10/22            21
21  2023/24      Pakistan   Afghanistan  2023/10/23            22
22  2023/24  South Africa    Bangladesh  2023/10/24            23
23  2023/24     Australia   Netherlands  2023/10/25            24
24  2023/24       England     Sri Lanka  2023/10/26            25
25  2023/24      Pakistan  South Africa  2023/10/27            26
26  2023/24     Australia   New Zealand  2023/10/28            27
27  2023/24   Netherlands    Bangladesh  2023/10/28            28
28  2023/24         India       England  2023/10/29            29
29  2023/24     Sri Lanka   Afghanistan  2023/10/30            30
30  2023/24    Bangladesh      Pakistan  2023/10/31            31
31  2023/24  South Africa   New Zealand  2023/11/01            32
32  2023/24         India     Sri Lanka  2023/11/02            33
33  2023/24   Netherlands   Afghanistan  2023/11/03            34
34  2023/24   New Zealand      Pakistan  2023/11/04            35
35  2023/24     Australia       England  2023/11/04            36
36  2023/24         India  South Africa  2023/11/05            37
37  2023/24     Sri Lanka    Bangladesh  2023/11/06            38
38  2023/24   Afghanistan     Australia  2023/11/07            39
39  2023/24       England   Netherlands  2023/11/08            40
40  2023/24     Sri Lanka   New Zealand  2023/11/09            41
41  2023/24   Afghanistan  South Africa  2023/11/10            42
42  2023/24    Bangladesh     Australia  2023/11/11            43
43  2023/24       England      Pakistan  2023/11/11            44
44  2023/24         India   Netherlands  2023/11/12            45
45  2023/24         India   New Zealand  2023/11/15            46
46  2023/24  South Africa     Australia  2023/11/16            47
47  2023/24         India     Australia  2023/11/19            48

                                                venue        city  \
0                               Narendra Modi Stadium   Ahmedabad
1                  Rajiv Gandhi International Stadium   Hyderabad
2        Himachal Pradesh Cricket Association Stadium  Dharamsala
3                                Arun Jaitley Stadium       Delhi
4                              MA Chidambaram Stadium     Chennai
5                  Rajiv Gandhi International Stadium   Hyderabad
6        Himachal Pradesh Cricket Association Stadium  Dharamsala
7                  Rajiv Gandhi International Stadium   Hyderabad
8                                Arun Jaitley Stadium       Delhi
9   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     Lucknow
10                             MA Chidambaram Stadium     Chennai
11                              Narendra Modi Stadium   Ahmedabad
12                               Arun Jaitley Stadium       Delhi
13  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     Lucknow
14       Himachal Pradesh Cricket Association Stadium  Dharamsala
15                             MA Chidambaram Stadium     Chennai
16            Maharashtra Cricket Association Stadium        Pune
17                              M Chinnaswamy Stadium   Bengaluru
18  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     Lucknow
19                                   Wankhede Stadium      Mumbai
20       Himachal Pradesh Cricket Association Stadium  Dharamsala
21                             MA Chidambaram Stadium     Chennai
22                                   Wankhede Stadium      Mumbai
23                               Arun Jaitley Stadium       Delhi
24                              M Chinnaswamy Stadium   Bengaluru
25                             MA Chidambaram Stadium     Chennai
26       Himachal Pradesh Cricket Association Stadium  Dharamsala
27                                       Eden Gardens     Kolkata
28  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     Lucknow
29            Maharashtra Cricket Association Stadium        Pune
30                                       Eden Gardens     Kolkata
31            Maharashtra Cricket Association Stadium        Pune
32                                   Wankhede Stadium      Mumbai
33  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     Lucknow
34                              M Chinnaswamy Stadium   Bengaluru
35                              Narendra Modi Stadium   Ahmedabad
36                                       Eden Gardens     Kolkata
37                               Arun Jaitley Stadium       Delhi
38                                   Wankhede Stadium      Mumbai
39            Maharashtra Cricket Association Stadium        Pune
40                              M Chinnaswamy Stadium   Bengaluru
41                              Narendra Modi Stadium   Ahmedabad
42            Maharashtra Cricket Association Stadium        Pune
43                                       Eden Gardens     Kolkata
44                              M Chinnaswamy Stadium   Bengaluru
45                                   Wankhede Stadium      Mumbai
46                                       Eden Gardens     Kolkata
47                              Narendra Modi Stadium   Ahmedabad

     toss_winner toss_decision     player_of_match          umpire1  \
0    New Zealand         field          R Ravindra  HDPK Dharmasena
1    Netherlands         field        Saud Shakeel     AT Holdstock
2     Bangladesh         field  Mehedi Hasan Miraz        JS Wilson
3      Sri Lanka         field          AK Markram   RK Illingworth
4      Australia           bat            KL Rahul      CB Gaffaney
5    Netherlands         field          MJ Santner       PR Reiffel
6     Bangladesh         field            DJ Malan       Ahsan Raza
7      Sri Lanka           bat     Mohammad Rizwan         AG Wharf
8    Afghanistan           bat           RG Sharma         MA Gough
9      Australia         field           Q de Kock        JS Wilson
10   New Zealand         field         LH Ferguson  HDPK Dharmasena
11         India         field           JJ Bumrah        M Erasmus
12       England         field    Mujeeb Ur Rahman        RJ Tucker
13     Sri Lanka           bat             A Zampa      CB Gaffaney
14  South Africa         field          SA Edwards         MA Gough
15   Afghanistan         field         GD Phillips        JS Wilson
16    Bangladesh           bat             V Kohli     AT Holdstock
17      Pakistan         field           DA Warner         CM Brown
18   Netherlands           bat    S Samarawickrama       Ahsan Raza
19       England         field           H Klaasen  HDPK Dharmasena
20         India         field      Mohammed Shami     AT Holdstock
21      Pakistan           bat      Ibrahim Zadran       PR Reiffel
22  South Africa           bat           Q de Kock       Ahsan Raza
23     Australia           bat          GJ Maxwell         MA Gough
24       England           bat        CBRLS Kumara     AT Holdstock
25      Pakistan           bat            T Shamsi         AG Wharf
26   New Zealand         field             TM Head        M Erasmus
27   Netherlands           bat     PA van Meekeren        JS Wilson
28       England         field           RG Sharma     AT Holdstock
29   Afghanistan         field    Fazalhaq Farooqi      CB Gaffaney
30    Bangladesh           bat        Fakhar Zaman      Nitin Menon
31   New Zealand         field   HE van der Dussen       Ahsan Raza
32     Sri Lanka         field      Mohammed Shami         CM Brown
33   Netherlands           bat       Mohammad Nabi      Nitin Menon
34      Pakistan         field        Fakhar Zaman         P Wilson
35       England         field             A Zampa      CB Gaffaney
36         India           bat             V Kohli  HDPK Dharmasena
37    Bangladesh         field     Shakib Al Hasan        M Erasmus
38   Afghanistan           bat          GJ Maxwell         AG Wharf
39       England           bat           BA Stokes       Ahsan Raza
40   New Zealand         field            TA Boult     AT Holdstock
41   Afghanistan           bat   HE van der Dussen         CM Brown
42     Australia         field            MR Marsh       Ahsan Raza
43       England           bat           DJ Willey         P Wilson
44         India           bat             SS Iyer      CB Gaffaney
45         India           bat      Mohammed Shami   RK Illingworth
46  South Africa           bat             TM Head      Nitin Menon
47     Australia         field             TM Head   RK Illingworth

             umpire2         reserve_umpire  match_referee        winner  \
0        Nitin Menon           Sharfuddoula      J Srinath   New Zealand
1           CM Brown             PR Reiffel       JJ Crowe      Pakistan
2    HDPK Dharmasena              M Erasmus     AJ Pycroft    Bangladesh
3       Sharfuddoula               AG Wharf      J Srinath  South Africa
4   RA Kettleborough           AT Holdstock  RB Richardson         India
5          RJ Tucker            Nitin Menon     AJ Pycroft   New Zealand
6           P Wilson        HDPK Dharmasena      J Srinath       England
7        CB Gaffaney              RJ Tucker     AJ Pycroft      Pakistan
8         PR Reiffel           Sharfuddoula       JJ Crowe         India
9     RK Illingworth               CM Brown      J Srinath  South Africa
10       Nitin Menon               AG Wharf  RB Richardson   New Zealand
11    RK Illingworth            CB Gaffaney     AJ Pycroft         India
12      Sharfuddoula               P Wilson       JJ Crowe   Afghanistan
13         JS Wilson                    NaN  RB Richardson     Australia
14  RA Kettleborough             Ahsan Raza       JJ Crowe   Netherlands
15          P Wilson          J Madanagopal      J Srinath   New Zealand
16  RA Kettleborough              M Erasmus     AJ Pycroft         India
17    RK Illingworth          J Madanagopal  RB Richardson     Australia
18         M Erasmus            CB Gaffaney       JJ Crowe     Sri Lanka
19       Nitin Menon              JS Wilson      J Srinath  South Africa
20          MA Gough            Praveen Sen     AJ Pycroft         India
21         RJ Tucker        HDPK Dharmasena  RB Richardson   Afghanistan
22         JS Wilson  KN Ananthapadmanabhan       JJ Crowe  South Africa
23      Sharfuddoula            Nitin Menon     AJ Pycroft     Australia
24          CM Brown              RJ Tucker      J Srinath     Sri Lanka
25        PR Reiffel       RA Kettleborough  RB Richardson  South Africa
26      Sharfuddoula               MA Gough     AJ Pycroft     Australia
27          P Wilson            CB Gaffaney       JJ Crowe   Netherlands
28         RJ Tucker               CM Brown  RB Richardson         India
29    RK Illingworth              M Erasmus      J Srinath   Afghanistan
30  RA Kettleborough             PR Reiffel     AJ Pycroft      Pakistan
31   HDPK Dharmasena               P Wilson  RB Richardson  South Africa
32        PR Reiffel         RK Illingworth       JJ Crowe         India
33      Sharfuddoula        HDPK Dharmasena      J Srinath   Afghanistan
34  RA Kettleborough              JS Wilson  RB Richardson      Pakistan
35         M Erasmus             Ahsan Raza       JJ Crowe     Australia
36        PR Reiffel               AG Wharf     AJ Pycroft         India
37    RK Illingworth           AT Holdstock  RB Richardson    Bangladesh
38          MA Gough           Sharfuddoula       JJ Crowe     Australia
39         RJ Tucker               P Wilson     AJ Pycroft       England
40         JS Wilson             PR Reiffel      J Srinath   New Zealand
41       Nitin Menon            CB Gaffaney       JJ Crowe  South Africa
42         M Erasmus       RA Kettleborough     AJ Pycroft     Australia
43         RJ Tucker             PR Reiffel      J Srinath       England
44          MA Gough               CM Brown  RB Richardson         India
45         RJ Tucker           AT Holdstock     AJ Pycroft         India
46  RA Kettleborough               MA Gough      J Srinath     Australia
47  RA Kettleborough            CB Gaffaney     AJ Pycroft     Australia

    winner_runs  winner_wickets  match_type
0           NaN             9.0       Group
1          81.0             NaN       Group
2           NaN             6.0       Group
3         102.0             NaN       Group
4           NaN             6.0       Group
5          99.0             NaN       Group
6         137.0             NaN       Group
7           NaN             6.0       Group
8           NaN             8.0       Group
9         134.0             NaN       Group
10          NaN             8.0       Group
11          NaN             7.0       Group
12         69.0             NaN       Group
13          NaN             5.0       Group
14         38.0             NaN       Group
15        149.0             NaN       Group
16          NaN             7.0       Group
17         62.0             NaN       Group
18          NaN             5.0       Group
19        229.0             NaN       Group
20          NaN             4.0       Group
21          NaN             8.0       Group
22        149.0             NaN       Group
23        309.0             NaN       Group
24          NaN             8.0       Group
25          NaN             1.0       Group
26          5.0             NaN       Group
27         87.0             NaN       Group
28        100.0             NaN       Group
29          NaN             7.0       Group
30          NaN             7.0       Group
31        190.0             NaN       Group
32        302.0             NaN       Group
33          NaN             7.0       Group
34         21.0             NaN       Group
35         33.0             NaN       Group
36        243.0             NaN       Group
37          NaN             3.0       Group
38          NaN             3.0       Group
39        160.0             NaN       Group
40          NaN             5.0       Group
41          NaN             5.0       Group
42          NaN             8.0       Group
43         93.0             NaN       Group
44        160.0             NaN       Group
45         70.0             NaN  Semi Final
46          NaN             3.0  Semi Final
47          NaN             6.0       Final

In [28]:
#9.What kind of question can be asked, should we ask. Does the dataset suits the question we are asking?
#ques1:Which team won the most matches?
print(df["winner"].value_counts())
#ques2: Who won the most Player of the Match awards?
print(df["player_of_match"].value_counts().head())

winner
India           10
Australia        9
South Africa     7
New Zealand      5
Pakistan         4
Afghanistan      4
England          3
Bangladesh       2
Netherlands      2
Sri Lanka        2
Name: count, dtype: int64
player_of_match
Mohammed Shami    3
TM Head           3
A Zampa           2
RG Sharma         2
V Kohli           2
Name: count, dtype: int64

From the dataset analysis,it is suitable for any stats we want to know regarding the tournament